### ISSUE TITLE
books.json?

### ISSUE THREAD

**Issue by tomByrer** [una/una.im#1]
Is this a new standard to share reading lists, similar to `/uses` is for what hardware & software people use to code & podcast with?

**Comment by una** [comment]
This is a temporary file, I have a [Notion doc](https://unakrav.notion.site/532416add66d48a8b881bd2d088916bf?v=9128f9841ea04dd6b65d8ae1e631f436) I use to track books and this is the export of that Notion doc. Ideally, I want this data to be dynamic (and this is the eventual plan using Notion's API)

**Comment by tomByrer** [comment]
Ah, the olde '`.JSON` then live CRUD' trick!  My fav :)
I had thought about Notion before also, but had privacy concerns.  I might have to try [AFFiNE](https://affine.pro/content/blog/downhills-release-announcement/index).

Thanks for the reply, & once my blog is rolling, I'll ping you with Container Queries tooling post if you don't mind.
